DROP TABLE IF EXISTS entrata.report_pre_lease_details_by_property CASCADE;

CREATE TABLE entrata.report_pre_lease_details_by_property (
  report_date DATE NOT NULL DEFAULT CURRENT_DATE,
  property_id INTEGER NOT NULL,
  property_name TEXT NOT NULL,
  bldg_unit TEXT NOT NULL,
  unit TEXT,
  unit_type TEXT NOT NULL,
  floorplan_name TEXT,
  unit_status TEXT NOT NULL,
  bldg TEXT,
  charge_code TEXT NOT NULL,
  resident_id INTEGER,
  resident_name TEXT,
  resident_email TEXT,
  resident_phone TEXT,
  resident_gender TEXT,
  student_id_number TEXT,
  lease_id TEXT NOT NULL,
  lease_status TEXT,
  lease_sub_status TEXT,
  lease_occupancy_type TEXT,
  lease_term_name TEXT,
  lease_term_month INTEGER,
  space_option TEXT,
  leasing_agent TEXT,
  ledger_name TEXT,
  lease_start_date DATE,
  lease_end_date DATE,
  lease_started_on_date DATE,
  lease_partially_completed_on_date DATE,
  lease_completed_on_date DATE,
  lease_approved_on_date DATE,
  move_in_date DATE,
  deposit_charged NUMERIC NOT NULL,
  deposit_held NUMERIC NOT NULL,
  market_rent NUMERIC NOT NULL,
  budgeted_rent NUMERIC NOT NULL,
  scheduled_rent NUMERIC NOT NULL,
  advertised_rate NUMERIC NOT NULL,
  actual_charges NUMERIC NOT NULL,
  scheduled_rent_total NUMERIC NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (report_date, property_id, bldg_unit, unit_type, lease_id, charge_code)
);

CREATE INDEX idx_report_pre_lease_details_by_property_report_date ON entrata.report_pre_lease_details_by_property (report_date);
