CREATE TABLE entrata.floorplans (
  floorplan_id INTEGER NOT NULL PRIMARY KEY,
  property_id INTEGER NOT NULL REFERENCES entrata.properties(property_id),
  unit_type_id INTEGER REFERENCES entrata.unit_types(unit_type_id),
  floorplan_name TEXT NOT NULL,
  unit_type_name TEXT,
  is_disabled BOOLEAN DEFAULT FALSE,
  total_units_count INTEGER,
  available_units_count INTEGER,
  number_of_bedrooms INTEGER,
  number_of_bathrooms INTEGER,
  min_square_feet NUMERIC,
  max_square_feet NUMERIC,
  avg_square_feet NUMERIC,
  min_market_rent NUMERIC,
  max_market_rent NUMERIC,
  avg_market_rent NUMERIC,
  floorplan_description TEXT,
  floorplan_image_url TEXT,
  floorplan_image_caption TEXT,
  floorplan_image_description TEXT,
  floorplan_image_format TEXT,
  floorplan_image_width INTEGER,
  floorplan_image_height INTEGER,
  floorplan_image_is_default BOOLEAN DEFAULT TRUE,
  floorplan_image_is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
