DROP TABLE IF EXISTS entrata.pre_lease_summary_by_unit CASCADE;

CREATE TABLE IF NOT EXISTS entrata.pre_lease_summary_by_unit (
    report_date DATE NOT NULL,
    property_id INTEGER NOT NULL REFERENCES entrata.properties(property_id),
    property_name TEXT NOT NULL,
    unit_type TEXT NOT NULL,
    avg_sqft NUMERIC DEFAULT 0,
    avg_advertised_rate NUMERIC DEFAULT 0,
    total_unit_count INTEGER DEFAULT 0,
    excluded_unit_count INTEGER DEFAULT 0,
    rentable_unit_count INTEGER DEFAULT 0,
    occupied_count INTEGER DEFAULT 0,
    available_count INTEGER DEFAULT 0,
    total_scheduled_rent NUMERIC DEFAULT 0,
    yoy_variance NUMERIC DEFAULT 0,
    avg_scheduled_rent NUMERIC DEFAULT 0,
    started_new_count_prior INTEGER DEFAULT 0,
    started_new_count INTEGER DEFAULT 0,
    started_renewal_count_prior INTEGER DEFAULT 0,
    started_renewal_count INTEGER DEFAULT 0,
    started_count_prior INTEGER DEFAULT 0,
    started_count INTEGER DEFAULT 0,
    started_percent NUMERIC DEFAULT 0,
    partially_completed_new_count_prior INTEGER DEFAULT 0,
    partially_completed_new_count INTEGER DEFAULT 0,
    partially_completed_renewal_count_prior INTEGER DEFAULT 0,
    partially_completed_renewal_count INTEGER DEFAULT 0,
    partially_completed_count_prior INTEGER DEFAULT 0,
    partially_completed_count INTEGER DEFAULT 0,
    partially_completed_percent NUMERIC DEFAULT 0,
    completed_new_count_prior INTEGER DEFAULT 0,
    completed_new_count INTEGER DEFAULT 0,
    completed_renewal_count_prior INTEGER DEFAULT 0,
    completed_renewal_count INTEGER DEFAULT 0,
    completed_count_prior INTEGER DEFAULT 0,
    completed_count INTEGER DEFAULT 0,
    completed_percent NUMERIC DEFAULT 0,
    approved_new_count_prior INTEGER DEFAULT 0,
    approved_new_count INTEGER DEFAULT 0,
    approved_renewal_count_prior INTEGER DEFAULT 0,
    approved_renewal_count INTEGER DEFAULT 0,
    approved_count_prior INTEGER DEFAULT 0,
    approved_count INTEGER DEFAULT 0,
    approved_percent NUMERIC DEFAULT 0,
    preleased_new_count_prior INTEGER DEFAULT 0,
    preleased_new_count INTEGER DEFAULT 0,
    preleased_renewal_count_prior INTEGER DEFAULT 0,
    preleased_renewal_count INTEGER DEFAULT 0,
    preleased_count_prior INTEGER DEFAULT 0,
    preleased_count INTEGER DEFAULT 0,
    preleased_percent_prior NUMERIC DEFAULT 0,
    preleased_percent NUMERIC DEFAULT 0,

    PRIMARY KEY (report_date, property_id, unit_type)
);
