DROP TABLE IF EXISTS entrata.pre_lease_report_details CASCADE;

CREATE TABLE IF NOT EXISTS entrata.pre_lease_report_details (
    report_date DATE,
    property_id INTEGER NOT NULL REFERENCES entrata.properties(property_id),
    property_name TEXT NOT NULL,
    bldg_unit TEXT,
    unit_type TEXT,
    unit_status TEXT DEFAULT NULL,
    floorplan_name TEXT DEFAULT NULL,
    sqft NUMERIC(10, 2),
    resident_id INTEGER,
    resident_name TEXT,
    resident_email TEXT,
    resident_phone TEXT,
    resident_gender TEXT,
    lease_id TEXT,
    lease_status TEXT,
    lease_sub_status TEXT,
    lease_occupancy_type TEXT,
    lease_term_name TEXT,
    lease_term_month INTEGER,
    space_option_preferred TEXT,
    space_option TEXT,
    lease_start_date DATE,
    lease_end_date DATE,
    lease_started_on_date DATE,
    lease_partially_completed_on_date DATE,
    lease_completed_on_date DATE,
    lease_approved_on_date DATE,
    move_in_date DATE,
    leasing_agent TEXT DEFAULT NULL,
    deposit_charged NUMERIC(10, 2),
    deposit_held NUMERIC(10, 2),
    market_rent NUMERIC(10, 2),
    budgeted_rent NUMERIC(10, 2),
    advertised_rate NUMERIC(10, 2),
    ledger_name TEXT DEFAULT NULL,
    charge_code TEXT,
    scheduled_rent NUMERIC(10, 2),
    actual_charges NUMERIC(10, 2),
    scheduled_rent_total NUMERIC(10, 2),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (report_date, property_id, unit_type, resident_id, lease_id, charge_code)
);
