DROP TABLE IF EXISTS entrata.report_pre_lease_summary_by_property CASCADE;

CREATE TABLE entrata.report_pre_lease_summary_by_property (
  report_date DATE NOT NULL,
  property_id INTEGER NOT NULL,
  property_name TEXT NOT NULL,
  total_unit_count INTEGER NOT NULL,
  excluded_unit_count INTEGER NOT NULL,
  rentable_unit_count INTEGER NOT NULL,
  occupied_unit_count INTEGER NOT NULL,
  available_unit_count INTEGER NOT NULL,
  total_scheduled_rent NUMERIC NOT NULL,
  avg_sqft NUMERIC NOT NULL,
  avg_advertised_rate NUMERIC NOT NULL,
  avg_scheduled_rent NUMERIC NOT NULL,
  started_new_count_prior INTEGER NOT NULL,
  started_new_count INTEGER NOT NULL,
  started_renewal_count_prior INTEGER NOT NULL,
  started_renewal_count INTEGER NOT NULL,
  started_count_prior INTEGER NOT NULL,
  started_count INTEGER NOT NULL,
  started_percent NUMERIC NOT NULL,
  partially_completed_new_count_prior INTEGER NOT NULL,
  partially_completed_new_count INTEGER NOT NULL,
  partially_completed_renewal_count_prior INTEGER NOT NULL,
  partially_completed_renewal_count INTEGER NOT NULL,
  partially_completed_count_prior INTEGER NOT NULL,
  partially_completed_count INTEGER NOT NULL,
  partially_completed_percent NUMERIC NOT NULL,
  completed_new_count_prior INTEGER NOT NULL,
  completed_new_count INTEGER NOT NULL,
  completed_renewal_count_prior INTEGER NOT NULL,
  completed_renewal_count INTEGER NOT NULL,
  completed_count_prior INTEGER NOT NULL,
  completed_count INTEGER NOT NULL,
  completed_percent NUMERIC NOT NULL,
  approved_new_count_prior INTEGER NOT NULL,
  approved_new_count INTEGER NOT NULL,
  approved_renewal_count_prior INTEGER NOT NULL,
  approved_renewal_count INTEGER NOT NULL,
  approved_count_prior INTEGER NOT NULL,
  approved_count INTEGER NOT NULL,
  approved_percent NUMERIC NOT NULL,
  preleased_new_count_prior INTEGER NOT NULL,
  preleased_new_count INTEGER NOT NULL,
  preleased_renewal_count_prior INTEGER NOT NULL,
  preleased_renewal_count INTEGER NOT NULL,
  preleased_count_prior INTEGER NOT NULL,
  preleased_count INTEGER NOT NULL,
  preleased_percent_prior NUMERIC NOT NULL,
  preleased_percent NUMERIC NOT NULL,
  yoy_variance INTEGER NOT NULL,
  PRIMARY KEY (report_date, property_id)
);

CREATE INDEX idx_report_pre_lease_summary_by_property_report_date ON entrata.report_pre_lease_summary_by_property(report_date);
