services:
  app:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - R_CONFIG_ACTIVE=default
      - R_CONFIG_FILE=/etc/gmhdatahub/config.yml
    volumes:
      - .:/app
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
