#!/usr/bin/env bash

npm install -g rag-crawler

rag-crawler https://gmhcommunities.entrata.com/api/v1/ entrata.docs.json

# ⚙️  maxConnections=5 exclude='' extract=''
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/code-snippet
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getStatus
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getCompanyApplications
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/sendApplication
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/sendApplicantGeneralDetails
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/sendApplicationPets
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/sendApplicationAddOns
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/updateApplication
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/sendApplicationVehicles
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/sendApplicationEmployers
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getArCodes
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getMitsLeaseArTransactions
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getArInvoices
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getLeaseArTransactions
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getArPayments
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getCustomers
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/sendLeaseArTransactionReversals
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/sendLeaseArTransactions
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getMarketingPreferences
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getMarketingPreferencePickList
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getTestimonialPickLists
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getCustomerTestimonials
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/searchCustomers
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/sendCustomerTestimonials
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/updateCustomers
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getBudgetActuals
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/updateCustomerTestimonials
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/updatePropertyResponse
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getBankAccounts
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getApCodes
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getJobCategories
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getBudgets
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getGlTrees
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getGlTransactions
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getFinancialPickList
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/sendBudgets
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getTransactionTagLists
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/markGlTransactionsExported
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getJobs
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getJobCostBudgets
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/sendJournalEntries
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/updateBudgets
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getLeadEvents
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/applyQuote
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/generateQuotes
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getQuotes
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getLeadPickLists
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getLeads
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getMitsLeads
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/sendLeads
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getExpiringLeases
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/cancelLease
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/updateLeads
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getEvictedLeases
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/sendMitsLeads
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getLeaseDocuments
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getLeaseDocumentsList
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getLeasePickList
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getLeases
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getLeaseDetails
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getMitsLeases
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/moveInLease
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getRentersInsurancePolicies
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getParcelAlerts
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getMitsCollections
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/sendLeaseDocuments
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/sendLeaseActivities
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/onNoticeLease
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/moveOutLease
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/sendLeases
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/sendRentersInsurancePolicies
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/updateLease
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/sendScheduledCharges
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/updateScheduledCharges
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/sendRoommateGroups
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getWorkOrderPickLists
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getLeasingCenterPickLists
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getInspectionTemplates
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getCallLogs
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getInspections
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/insertPricing
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/sendWorkOrders
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getPricingPicklists
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/updateWorkOrders
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getWorkOrders
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getCalendarAvailability
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getFloorPlans
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getPetTypes
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getAmenityReservations
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/sendBudgetedRent
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getProperties
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getPropertyAddOns
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getPropertyAnnouncements
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getPropertyPickLists
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getPhoneNumber
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getWebsites
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getReservableAmenities
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/sendRentableItems
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getRentableItems
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/sendFloorplans
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getPropertyUnits
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getUnitsAvailabilityAndPricing
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getAmenities
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getSpecials
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getMitsPropertyUnits
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/sendPropertyUnits
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getUnitTypes
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getResponse
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/sendAmenities
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/updateAmenities
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getInvoices
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getReportData
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getReportList
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getReportInfo
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getDependentFilter
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getVendorPickLists
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getPoReceivingRecords
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getTaxFormData
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getVendorLocations
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getPurchaseOrders
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/markInvoicesExported
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/sendVendors
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/sendInvoices
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/sendPurchaseOrders
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/getVendors
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/updateVendors
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/updateInvoices
# 🚀 Crawled https://gmhcommunities.entrata.com/api/v1/documentation/voidApPayments
# ✨ Crawl completed
