INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Property', 'Transportation', 'University Shuttle', 'bus-front');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Property', 'Transportation', 'Private Shuttle', 'taxi-front');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Property', 'Transportation', 'Limited Access Gates', 'door-closed');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Property', 'Transportation', 'EV Charging Stations', 'plug');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Property', 'Transportation', 'Car Sharing Services', 'share');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Property', 'Fitness & Recreation', 'Fitness Center', 'universal-access');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Property', 'Fitness & Recreation', 'Game Room', 'controller');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Property', 'Fitness & Recreation', 'Pool', 'water');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Property', 'Fitness & Recreation', 'Hot Tub', 'droplet-half');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Property', 'Fitness & Recreation', 'Sauna/Spa', 'moisture');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Property', 'Fitness & Recreation', 'Cycling/Yoga Studio', 'bicycle');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Property', 'Fitness & Recreation', 'Sand Volleyball Court', 'dribbble');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Property', 'Fitness & Recreation', 'Basketball Court', 'trophy');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Property', 'Fitness & Recreation', 'Outdoor Grill Area', 'fire');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Property', 'Wellness & Beauty', 'Spray Tanning', 'droplet');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Property', 'Wellness & Beauty', 'UV Tanning', 'sun');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Property', 'Wellness & Beauty', 'Wellness Classes', 'heart-pulse');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Property', 'Work & Study', 'Computer Lounge', 'pc-display');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Property', 'Work & Study', 'Co-Working/Study Spaces', 'people');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Property', 'Work & Study', 'Free Printing', 'printer');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Property', 'Convenience & Services', '24hr Package System', 'box-seam');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Property', 'Convenience & Services', 'Smart Vending', 'cart');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Property', 'Convenience & Services', 'Mini Market', 'shop');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Property', 'Convenience & Services', 'Coffee Bar', 'cup-hot');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Property', 'Convenience & Services', 'Retail', 'bag');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Property', 'Convenience & Services', 'Movie Theatre', 'film');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Property', 'Convenience & Services', 'Rentable Guest Suite', 'house');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Property', 'Convenience & Services', '24hr Concierge', 'person-workspace');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Property', 'Pet Amenities', 'Pets Allowed', 'patch-check');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Property', 'Pet Amenities', 'Dog Wash', 'tropical-storm');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Property', 'Pet Amenities', 'Dog Park', 'tree');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Unit', 'Unit Amenities', 'Private Bathrooms', 'water');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Unit', 'Unit Amenities', 'Walk-in Closets', 'door-open');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Unit', 'Unit Amenities', 'Washer / Dryer in Unit', 'infinity');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Unit', 'Unit Amenities', 'Smart Home Technology', 'robot');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Unit', 'Unit Amenities', 'Smart Bedroom Locks', 'key');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Unit', 'Unit Amenities', 'Smart Unit Locks', 'key-fill');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Unit', 'Unit Amenities', 'Energy Efficient Appliances', 'lightning');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Unit', 'Unit Amenities', 'Stainless Steel Appliances', 'star');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Unit', 'Unit Amenities', 'Balconies', 'window');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Unit', 'Unit Amenities', 'Patios', 'door-open');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Unit', 'Unit Amenities', 'Backyards', 'tree');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Unit', 'Unit Amenities', 'TV Included in Rent', 'tv');
INSERT INTO survey.amenities (amenity_type, amenity_category, amenity_name, amenity_icon) VALUES ('Unit', 'Unit Amenities', 'Furniture Included in Rent', 'lamp');
