-- !preview conn=DBI::dbConnect(RSQLite::SQLite())

DROP TABLE IF EXISTS entrata.report_pre_lease_summary_by_property CASCADE;

CREATE TABLE entrata.report_pre_lease_summary_by_property (
  report_date DATE NOT NULL DEFAULT CURRENT_DATE,
  property_id INTEGER NOT NULL UNIQUE,
  property_name TEXT NOT NULL,
  -- property TEXT,
  -- property_subtotal TEXT,
  avg_sqft NUMERIC,
  avg_advertised_rate NUMERIC,
  units INTEGER,
  excluded_unit_count INTEGER,
  rentable_unit_count INTEGER,
  avg_scheduled_rent NUMERIC,
  occupied_count INTEGER,
  started_new_count_prior INTEGER,
  started_new_count INTEGER,
  started_renewal_count_prior INTEGER,
  started_renewal_count INTEGER,
  started_count_prior INTEGER,
  started_count INTEGER,
  started_percent NUMERIC,
  partially_completed_new_count_prior INTEGER,
  partially_completed_new_count INTEGER,
  partially_completed_renewal_count_prior INTEGER,
  partially_completed_renewal_count INTEGER,
  partially_completed_count_prior INTEGER,
  partially_completed_count INTEGER,
  partially_completed_percent NUMERIC,
  completed_new_count_prior INTEGER,
  completed_new_count INTEGER,
  completed_renewal_count_prior INTEGER,
  completed_renewal_count INTEGER,
  completed_count_prior INTEGER,
  completed_count INTEGER,
  completed_percent NUMERIC,
  approved_new_count_prior INTEGER,
  approved_new_count INTEGER,
  approved_renewal_count_prior INTEGER,
  approved_renewal_count INTEGER,
  approved_count_prior INTEGER,
  approved_count INTEGER,
  approved_percent NUMERIC,
  preleased_new_count_prior INTEGER,
  preleased_new_count INTEGER,
  preleased_renewal_count_prior INTEGER,
  preleased_renewal_count INTEGER,
  preleased_count_prior INTEGER,
  preleased_count INTEGER,
  preleased_percent_prior INTEGER,
  preleased_percent INTEGER,
  variance INTEGER,
  available_count INTEGER,
  scheduled_rent_total INTEGER
);
