name: Build Docker Container (GCP)

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PROJECT_ID: 'gmh-communities'
  REGION: 'us-east1'
  SERVICE: 'gmh-datahub'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/851121724994/locations/global/workloadIdentityPools/github/providers/github'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: 'github-actions-sa@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'

      - name: 'Setup gcloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Configure Docker'
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: 'Docker Auth'
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.auth_token }}'
          registry: '${{ env.REGION }}-docker.pkg.dev'

      - name: 'Check and Create Artifact Registry Repository'
        run: |
            if ! gcloud artifacts repositories describe ${{ env.SERVICE }} \
              --location=${{ env.REGION }} > /dev/null 2>&1; then
              echo "Repository does not exist. Creating..."
              gcloud artifacts repositories create ${{ env.SERVICE }} \
                --repository-format=docker \
                --location=${{ env.REGION }} \
                --description="Docker repository for ${{ env.SERVICE }}"
            else
              echo "Repository already exists. Skipping creation."
            fi

      - name: 'Build and Push Container'
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.SERVICE }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" -f ./app/Dockerfile ./app
          docker push "${DOCKER_TAG}"

      - name: 'Deploy to Cloud Run'
        id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.SERVICE }}:${{ github.sha }}'

      - name: 'Show output'
        run: echo ${{ steps.deploy.outputs.url }}
